<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Constants\" />
    <Folder Include="Enums\" />
    <Folder Include="Extensions\" />
    <Folder Include="Helpers\" />
    <Folder Include="Logging\" />
    <Folder Include="Models\Analysis\" />
    <Folder Include="Models\Versioning\" />
    <Folder Include="Models\Reporting\" />
    <Folder Include="Models\Workspace\" />
  </ItemGroup>

</Project>
