<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ToscaWorkspaceGuardian.Common\ToscaWorkspaceGuardian.Common.csproj" />
    <ProjectReference Include="..\ToscaWorkspaceGuardian.Core\ToscaWorkspaceGuardian.Core.csproj" />
    <ProjectReference Include="..\ToscaWorkspaceGuardian.RuleEngine\ToscaWorkspaceGuardian.RuleEngine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Html\" />
    <Folder Include="Models\" />
    <Folder Include="Pdf\" />
    <Folder Include="Templates\" />
  </ItemGroup>

</Project>
