<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ToscaWorkspaceGuardian.Common\ToscaWorkspaceGuardian.Common.csproj" />
    <ProjectReference Include="..\ToscaWorkspaceGuardian.Core\ToscaWorkspaceGuardian.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />

		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.10" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.10" />
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenTelemetry" Version="1.6.0" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.0.0-rc9" />
    <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.6.0" />
    <PackageReference Include="WPF-UI" Version="4.3.0" />
  </ItemGroup>

</Project>
